# Generated by Django 5.0 on 2025-11-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name_plural": "Matches"},
        ),
        migrations.AddField(
            model_name="match",
            name="user1_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="user2_notified",
            field=models.BooleanField(default=False),
        ),
    ]
