# Generated by Django 5.0 on 2025-11-06 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="location_lat",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="location_lng",
            new_name="longitude",
        ),
    ]
