# Generated by Django 5.0 on 2025-11-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_location_lat_profile_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="google_calendar_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="google_calendar_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="google_calendar_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
