# Generated by Django 5.0 on 2025-12-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_google_calendar_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="academic_info_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - Visible to everyone"),
                    ("matches", "Matches - Only visible to your matches"),
                    ("private", "Private - Not visible to anyone"),
                ],
                default="public",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - Visible to everyone"),
                    ("matches", "Matches - Only visible to your matches"),
                    ("private", "Private - Not visible to anyone"),
                ],
                default="public",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="courses_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - Visible to everyone"),
                    ("matches", "Matches - Only visible to your matches"),
                    ("private", "Private - Not visible to anyone"),
                ],
                default="public",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - Visible to everyone"),
                    ("matches", "Matches - Only visible to your matches"),
                    ("private", "Private - Not visible to anyone"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
